#!/usr/bin/env bash
# Wezterm Project - Start a new wezterm project

PROJECTS_DIR="/e/stproject/wezterm/projects"

project=""

if [[ "$1" == "g" ]]; then
  runtime_env="general"
elif [[ "$1" == "d" ]]; then
  runtime_env="docker"
else
  echo "No runtime environment provided: g(general)/d(docker)"
  exit
fi

if [[ -z "$2" ]]; then
  # List all files in projects directory. Only keep the file name without the extension
  project=$(find "$PROJECTS_DIR" -maxdepth 1 -type "f,l" -name "*.lua" -printf '%f\n' | sed "s/\.lua//" | fzf --cycle --layout=reverse)
else
  if [[ ! -e "$PROJECTS_DIR/$1.lua" ]]; then
    echo "The project file '$PROJECTS_DIR/$1.lua' not exists"
    exit 1
  fi
  project="$2"
fi

if [[ -z $project ]]; then
  echo "No project selected"
  exit 1
fi

WZ_PROJECT="$project" WZ_RUNTIME="$runtime_env" wezterm start --always-new-process &
#WZ_PROJECT="$project" wezterm cli spawn --new-window --workspace "abc"
