# ---------- Prefix ----------
# Use Ctrl+space as the tmux prefix

# --------------------------------------------------
# Window/Tab
# --------------------------------------------------

# Create new tab
map ctrl+space>c launch --type=tab --cwd=current

# Close current tab
map ctrl+space>& close_tab

# Switch to previous tab
map ctrl+space>p previous_tab

# Switch to next tab
map ctrl+space>n next_tab

# Switch to tab index: from 1 to 10
map ctrl+space>1 goto_tab 1
map ctrl+space>2 goto_tab 2
map ctrl+space>3 goto_tab 3
map ctrl+space>4 goto_tab 4
map ctrl+space>5 goto_tab 5
map ctrl+space>6 goto_tab 6
map ctrl+space>7 goto_tab 7
map ctrl+space>8 goto_tab 8
map ctrl+space>9 goto_tab 9
map ctrl+space>0 goto_tab 10

# --------------------------------------------------
# Panes
# --------------------------------------------------

# ---------- Split panes ----------

# Split pane horizontally
map ctrl+space>% launch --location=hsplit

# Split pane vertically
map ctrl+space>" launch --location=vsplit

# ---------- Pane navigation ----------

# Select the pane above the active pane
map ctrl+space>up neighboring_window up

# Select the pane below the active pane
map ctrl+space>down neighboring_window down

# Select the pane to the left of the active pane
map ctrl+space>left neighboring_window left

# Select the pane to the right of the active pane
map ctrl+space>right neighboring_window right

# ---------- Zoom current pane ----------
map ctrl+space>z toggle_layout stack

# ---------- Detach pane to new tab ----------
map ctrl+space>! detach_window new-tab

# ---------- Pane resizing ----------

# Resize the pane up
map ctrl+space>ctrl+up resize_window taller 5

# Resize the pane down
map ctrl+space>ctrl+down resize_window shorter 5

# Resize the pane left
map ctrl+space>ctrl+left resize_window narrower 5

# Resize the pane right
map ctrl+space>ctrl+right resize_window wider 5

# ---------- Move panes ----------

# Rotate panes counter-clockwise
map ctrl+space>{ move_window backward

# Rotate panes clockwise
map ctrl+space>} move_window forward

# ---------- Close pane ----------
map ctrl+space>x close_window

# ---------- Copy Mode ----------

# Open terminal buffer with "less" program
map ctrl+space>[ show_scrollback

# Open terminal buffer with "vim" program
map ctrl+space>ctrl+n launch --type=overlay --stdin-source=@screen_scrollback vim -

# Open terminal buffer with "nvim" program
# map ctrl+space>ctrl+n launch --type=overlay --stdin-source=@screen_scrollback nvim -

