#!/bin/bash

#--------------------------Start: HDD Partition Mount Error---------------------------
# If windows OS is used in dual boot system and shutdown/hibernate from windows OS, 
# then failed to mount hard disk partitions in linux OS. 
# To solve this issue, restart from windows OS to linux OS.
# If problem persists, from windows OS enable "fast-startup" and shutdown, 
# then start pc and disable "fast-startup" and shutdown, 
# then start pc and restart to linux OS.
#---------------------------End: HDD Partition Mount Error----------------------------

# Check hard disk partition list: `sudo fdisk -l`

sudo umount /dev/sdb2
sudo umount /dev/sdb4
sudo umount /dev/sdb5
sudo umount /dev/sdb6
